export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'
export const ASYNC_INCREMENT_COUNTER = 'ASYNC_INCREMENT_COUNTER'
export const ADD_TODO = 'ADD_TODO'
export const FILTER_SEARCH = 'FILTER_SEARCH'
export const REMOVE_TODO = 'REMOVE_TODO'

// API Based Cases
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE'
export const FETCH_LIST_USER_REQUEST = 'FETCH_LIST_USER_REQUEST'
export const FETCH_LIST_USER_SUCCESS = 'FETCH_LIST_USER_SUCCESS'
export const FETCH_LIST_USER_FAILURE = 'FETCH_LIST_USER_FAILURE'
export const FETCH_DELETE_USER_SUCCESS = 'FETCH_DELETE_USER_SUCCESS'
export const FETCH_DELETE_USER_FAILURE = 'FETCH_DELETE_USER_FAILURE'
export const FETCH_DELETE_USER_PENDING = 'FETCH_DELETE_USER_PENDING'
export const FETCH_CREATE_USER_SUCCESS = 'FETCH_CREATE_USER_SUCCESS'
export const FETCH_CREATE_USER_FAILURE = 'FETCH_CREATE_USER_FAILURE'
export const FETCH_CREATE_USER_PENDING = 'FETCH_CREATE_USER_PENDING'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING'

// ERRORS
export const SUCCESS = 'SUCCESS'
export const FAILURE = 'FAILURE'
export const FOLLOWING_ERROR_ENCOUNTERED = 'Following Error Encountered :'

// TO BE ADDEDIN CONFIGURATION FILE ONLY TEMPORARY ADDITION TO THIS FILE
export const API_LINK =
  'https://randomapi.com/api/6de6abfedb24f889e0b5f675edc50deb?fmt=raw&sole'

export const USERS_BACKEND =
  'http://localhost:9000/user-list/'

export const CREATE_TODO_ITEM =
  'http://localhost:9000/todo-items/'
