export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const ASYNC_INCREMENT_COUNTER = 'ASYNC_INCREMENT_COUNTER';
export const ADD_TODO = 'ADD_TODO';
export const FILTER_SEARCH = 'FILTER_SEARCH';
export const REMOVE_TODO = 'REMOVE_TODO';
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE';
//TO BE ADDED IN CONFIGURATION FILE ONLY TEMPORARY ADDITION TO THIS FILE
export const API_LINK =
  'https://randomapi.com/api/6de6abfedb24f889e0b5f675edc50deb?fmt=raw&sole'