export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const ASYNC_INCREMENT_COUNTER = 'ASYNC_INCREMENT_COUNTER';
export const ADD_TODO = 'ADD_TODO';
export const FILTER_SEARCH = 'FILTER_SEARCH';
export const REMOVE = 'REMOVE';